[versions]
java = "21"
quarkus = "3.12.1"

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
test-assertj = { module = "org.assertj:assertj-core", version = "3.26.0" }
test-mockito = { module = "org.mockito:mockito-core", version = "5.12.0" }
test-junit =    { module = "org.junit.jupiter:junit-jupiter", version = "5.10.3" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "6.10.0.202406032230-r" }
plugin-quarkus = { module = "io.quarkus:gradle-application-plugin", version.ref = "quarkus" }
test-archunit = {module = "com.tngtech.archunit:archunit-junit5", version = "1.3.0"}

[plugins]
